#pragma once
namespace nPhysics
{

	enum eConstraintType
	{
		CONSTRAINT_TYPE_BALL_AND_SOCKET,
		CONSTRAINT_TYPE_HINGE,
		CONSTRAINT_TYPE_FIXED,
		CONSTRAINT_TYPE_GEAR,
		CONSTRAINT_TYPE_CONE,
		CONSTRAINT_TYPE_DEGREES
	};

}